fuel_app:
  container_name: "fuel_app"
  build: ./app
  restart: always
  env_file: ./app/env
  links:
    - fuel_mysql:db
    - fuel_redis:redis
    - fuel_memcached:memcached
  volumes:
    - /var/run
    - ./fuel_project:/usr/src/app
    - ./app/php-fpm.d:/usr/local/etc/php-fpm.d

fuel_nginx:
  container_name: "fuel_nginx"
  build: ./nginx
  restart: always
  ports:
    - "80:80"
  links:
    - fuel_app:app
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/application.conf:/etc/nginx/conf.d/application.conf
  volumes_from:
    - fuel_app

fuel_mysql:
  container_name: "fuel_mysql"
  build: ./mysql
  restart: always
  ports:
    - "3306:3306"
  volumes_from:
    - fuel_storage

fuel_redis:
  container_name: "fuel_redis"
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
  volumes_from:
    - fuel_storage
  command: redis-server --appendonly yes

fuel_memcached:
  container_name: "fuel_memcached"
  image: memcached:latest
  restart: always
  ports:
    - '11211:11211'
  volumes_from:
    - fuel_storage

fuel_storage:
  build: ./storage
